name: coverage

on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.2.0
      env:
        CC_TEST_REPORTER_ID: e69352ed5eb922f14876e79f2393bcba2496824f15cb3334f263d4f8780eb0c8
        COV: 1
      with:
        coverageCommand: bundle exec rake test
