name: coverage

on: [push]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install --without=lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.2.0
      env:
        CC_TEST_REPORTER_ID: 05b92e17dbbc2f0094a0e9ef7afdade2e7d9f50c30cdd5d2a71b91a1451711ae
        COV: 1
      with:
        coverageCommand: bundle exec rake test
